### PR TITLE
fix(hasNotch): Add iPhone 13 lineup to list of devices with notch

### PR DESCRIPTION
**Pull request by rolfb**
## Description

iPhone 13 lineup is about a week out, so adding this to the device list for devices with notch.

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |
| Windows |    ✅     |

### CODE REVIEW

**Comment by rolfb** [comment]
Just out of curiosity, what is following Conventional Commits useful for? I sense a learning opportunity.

**Comment by schie** [comment]
> Just out of curiosity, what is following Conventional Commits useful for? I sense a learning opportunity.

@rolfb checkout [commitizen/cz-cli](https://github.com/commitizen/cz-cli)

**Review by mikehardy — APPROVED** [review]
Nice! Thanks

Conventional Commits, when followed strictly (a thing we enforce with a check here as you have found :-) ), allow you to infer the type of semantic version release (patch, feature, or breaking change) that is represented by a group of commits, which then allows you to automate releases completely when PRs are merged, via a github action that scans commit logs for conventional commits, infers the type of release and makes the correct version bump

You'll see it in action here - as soon as I merge this it'll do a patch release

**Comment by rolfb** [comment]
@mikehardy Appreciate the explanation, and thank you for the quick merge and release :)

**Comment by hiteshSavkare** [comment]
Hi @mikehardy
Just curious to know don't we require the IOS file changes for notch support? 
actually i am testing it on IOS 13 but always  returning me false 

I just found the reference here  how it was for IOS 12, there i can see IOS file changes 
https://github.com/react-native-device-info/react-native-device-info/pull/1099/files

**Comment by rolfb** [comment]
Seems like I missed a file 🥺

**Comment by hiteshSavkare** [comment]
> Hi @mikehardy && @rolfb
> Just curious to know don't we require the IOS file changes for notch support?
> actually i am testing it on IOS 13 but always returning me false
> 
> I just found the reference here how it was for IOS 12, there i can see IOS file changes
> https://github.com/react-native-device-info/react-native-device-info/pull/1099/files

seems like that, hope you will add that file soon, eagerly waiting for testing , thanks for your efforts

**Comment by rolfb** [comment]
@hiteshSavkare can you have a look at #1309 and see if that fixes things for you?

**Comment by hiteshSavkare** [comment]
> @hiteshSavkare can you have a look at #1309 and see if that fixes things for you?

@rolfb yes perfect, working as expected

**Comment by rolfb** [comment]
> @rolfb yes perfect, working as expected

@hiteshSavkare great! if you have a chance to verify that all four iPhone 13 devices are correctly mapped now I'd appreciate it 😊 I couldn't find official docs for firmware identifiers but it's highly likely that they are following the same pattern.

**Pull request merged**
