### PR TITLE
fix(android): avoid ANR with use of background thread in RNInstallReferrerClient

### PR DESCRIPTION
**Pull request by pSapien**
#### Overview:

This PR addresses an ANR (Application Not Responding) issue in the RNInstallReferrerClient class by refactoring network operations to run in background threads.

I can confirm that I have used this code in our react-native mobile app, and released it to production.
We haven't had any ANRs as of now.

#### Details:

1. Introduced an ExecutorService to manage background threads.
2. Moved the initialization of InstallReferrerClient and the invocation of startConnection to a background thread.
3. Ensured that the `onInstallReferrerSetupFinished` and `onInstallReferrerServiceDisconnected` callbacks were posted back to the main thread using a Handler. The network call within onInstallReferrerSetupFinished is now executed in a background thread to prevent blocking the main thread.

This was done as per the comment in https://github.com/react-native-device-info/react-native-device-info/issues/1377#issuecomment-1048751264

### CODE REVIEW

**Comment by Ananthakr-Jupiter** [comment]
@pSapien when can we expect this to be merged?

**Comment by pSapien** [comment]
> @pSapien when can we expect this to be merged?

For now, you could write a script that copies and replaces the `RNInstallReferrerClient.java` in your node_modules folder, and then build the project.

**Comment by Ananthakr-Jupiter** [comment]
@pSapien We have created a patch for this with your changes. We are using `v8.7.1`, since the file is unmodified since 8.x versions, your changes apply fine. 

Here is the patch if anyone looking for it.

```
diff --git a/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNInstallReferrerClient.java b/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNInstallReferrerClient.java
index d02152b..d612ac0 100644
--- a/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNInstallReferrerClient.java
+++ b/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNInstallReferrerClient.java
@@ -3,11 +3,14 @@ package com.learnium.RNDeviceInfo;
 import android.content.SharedPreferences;
 import android.content.Context;
 import android.util.Log;
+import android.os.Handler;
+import android.os.Looper;
 
 import java.lang.reflect.InvocationHandler;
 import java.lang.reflect.Method;
 import java.lang.reflect.Proxy;
-
+import java.util.concurrent.ExecutorService;
+import java.util.concurrent.Executors;
 
 public class RNInstallReferrerClient {
   private static Class<?> InstallReferrerClientClazz;
@@ -27,6 +30,8 @@ public class RNInstallReferrerClient {
   private final SharedPreferences sharedPreferences;
   private Object mReferrerClient;
   private Object installReferrerStateListener;
+  private final ExecutorService executorService = Executors.newSingleThreadExecutor();
+  private final Handler mainHandler = new Handler(Looper.getMainLooper());
 
   // From InstallReferrerClient.InstallReferrerResponse
   private static final int R_RESPONSE_OK                    = 0;
@@ -40,26 +45,28 @@ public class RNInstallReferrerClient {
       return;
     }
 
-    try {
-      // Build the InstallReferrerClient instance.
-      Method newBuilderMethod = InstallReferrerClientClazz.getMethod("newBuilder", Context.class);
-      Object builder = newBuilderMethod.invoke(null, context);
-      Method buildMethod = builder.getClass().getMethod("build");
-      mReferrerClient = buildMethod.invoke(builder);
-
-      // Create the InstallReferrerStateListener instance using a Proxy.
-      installReferrerStateListener = Proxy.newProxyInstance(
-          InstallReferrerStateListenerClazz.getClassLoader(),
-          new Class[]{InstallReferrerStateListenerClazz},
-          new InstallReferrerStateListenerProxy());
-
-      // Call startConnection on the client instance.
-      Method startConnectionMethod = InstallReferrerClientClazz.getMethod("startConnection", InstallReferrerStateListenerClazz);
-      startConnectionMethod.invoke(mReferrerClient, installReferrerStateListener);
-    } catch (Exception e) {
-      System.err.println("RNInstallReferrerClient exception. getInstallReferrer will be unavailable: " + e.getMessage());
-      e.printStackTrace(System.err);
-    }
+    executorService.execute(() -> {
+      try {
+        // Build the InstallReferrerClient instance.
+        Method newBuilderMethod = InstallReferrerClientClazz.getMethod("newBuilder", Context.class);
+        Object builder = newBuilderMethod.invoke(null, context);
+        Method buildMethod = builder.getClass().getMethod("build");
+        mReferrerClient = buildMethod.invoke(builder);
+
+        // Create the InstallReferrerStateListener instance using a Proxy.
+        installReferrerStateListener = Proxy.newProxyInstance(
+            InstallReferrerStateListenerClazz.getClassLoader(),
+            new Class[]{InstallReferrerStateListenerClazz},
+            new InstallReferrerStateListenerProxy());
+
+        // Call startConnection on the client instance.
+        Method startConnectionMethod = InstallReferrerClientClazz.getMethod("startConnection", InstallReferrerStateListenerClazz);
+        startConnectionMethod.invoke(mReferrerClient, installReferrerStateListener);
+      } catch (Exception e) {
+        System.err.println("RNInstallReferrerClient exception. getInstallReferrer will be unavailable: " + e.getMessage());
+        e.printStackTrace(System.err);
+      }
+    });
   }
 
   private class InstallReferrerStateListenerProxy implements InvocationHandler {
@@ -67,11 +74,22 @@ public class RNInstallReferrerClient {
     public Object invoke(Object o, Method method, Object[] args) throws Throwable {
       String methodName = method.getName();
       try {
-          if (methodName.equals("onInstallReferrerSetupFinished") && args != null && args[0] instanceof Integer) {
-            onInstallReferrerSetupFinished((Integer) args[0]);
-          } else if (methodName.equals("onInstallReferrerServiceDisconnected")) {
-            onInstallReferrerServiceDisconnected();
-          }
+        if (methodName.equals("onInstallReferrerSetupFinished") && args != null && args[0] instanceof Integer) {
+          int responseCode = (Integer) args[0];
+          mainHandler.post(new Runnable() {
+            @Override
+            public void run() {
+              onInstallReferrerSetupFinished(responseCode);
+            }
+          });
+        } else if (methodName.equals("onInstallReferrerServiceDisconnected")) {
+          mainHandler.post(new Runnable() {
+            @Override
+            public void run() {
+              onInstallReferrerServiceDisconnected();
+            }
+          });
+        }
       } catch (Exception e) {
         throw new RuntimeException("unexpected invocation exception: " + e.getMessage());
       }
@@ -83,23 +101,25 @@ public class RNInstallReferrerClient {
       switch (responseCode) {
         case R_RESPONSE_OK:
           // Connection established
-          try {
-            //if (BuildConfig.DEBUG)
-            Log.d("InstallReferrerState", "OK");
-            Method getInstallReferrerMethod = InstallReferrerClientClazz.getMethod("getInstallReferrer");
-            Object response = getInstallReferrerMethod.invoke(mReferrerClient);
-            Method getInstallReferrerMethod2 = ReferrerDetailsClazz.getMethod("getInstallReferrer");
-            String referrer = (String) getInstallReferrerMethod2.invoke(response);
-            SharedPreferences.Editor editor = sharedPreferences.edit();
-            editor.putString("installReferrer", referrer);
-            editor.apply();
-
-            Method endConnectionMethod = InstallReferrerClientClazz.getMethod("endConnection");
-            endConnectionMethod.invoke(mReferrerClient);
-          } catch (Exception e) {
-            System.err.println("RNInstallReferrerClient exception. getInstallReferrer will be unavailable: " + e.getMessage());
-            e.printStackTrace(System.err);
-          }
+          executorService.execute(() -> {
+            try {
+              //if (BuildConfig.DEBUG)
+              Log.d("InstallReferrerState", "OK");
+              Method getInstallReferrerMethod = InstallReferrerClientClazz.getMethod("getInstallReferrer");
+              Object response = getInstallReferrerMethod.invoke(mReferrerClient);
+              Method getInstallReferrerMethod2 = ReferrerDetailsClazz.getMethod("getInstallReferrer");
+              String referrer = (String) getInstallReferrerMethod2.invoke(response);
+              SharedPreferences.Editor editor = sharedPreferences.edit();
+              editor.putString("installReferrer", referrer);
+              editor.apply();
+
+              Method endConnectionMethod = InstallReferrerClientClazz.getMethod("endConnection");
+              endConnectionMethod.invoke(mReferrerClient);
+            } catch (Exception e) {
+              System.err.println("RNInstallReferrerClient exception. getInstallReferrer will be unavailable: " + e.getMessage());
+              e.printStackTrace(System.err);
+            }
+          });
           break;
         case R_RESPONSE_FEATURE_NOT_SUPPORTED:
           //if (BuildConfig.DEBUG)

```

**Review by mikehardy — APPROVED** [review]
Looks good - sorry for the delay, appreciate the patience
will close / reopen just to run CI but should merge+release after

**Pull request merged**
