### PR TITLE
1119: Change keychain access control

### LINKED ISSUE #1119: Weak Keychain Protection Class kSecAttrAccessibleAlways
This package uses [`kSecAttrAccessibleAlways` keychain security attribute](https://github.com/react-native-device-info/react-native-device-info/blob/master/ios/RNDeviceInfo/DeviceUID.m#L94) which is [deprecated in iOS 9](https://developer.apple.com/documentation/security/ksecattraccessiblealways) and not recommended for application use. 

Essentially this is a security risk which allows data in the keychain be accessible regardless if a device is locked.

### PR DESCRIPTION
**Pull request by dmitry-bluescape**
## Description

Fixes #1119

Could you help me test it?

### CODE REVIEW

**Comment by dmitry-bluescape** [comment]
The change is for iOS only, I'm not sure why windows tests fail

**Comment by mikehardy** [comment]
No worries on the windows CI failure, we have a separate MASSIVE batch of windows changes pending that I need to merge, and it will take care of that - I'll put this in the review queue - thanks for taking the time to make a PR !

**Review by mikehardy — APPROVED** [review]
Yeah - combining your comment explaining the history and the options, I think this is best - looks good to me, I will test and do a release as soon as I can, in the meantime https://github.com/ds300/patch-package can be used if needed

**Comment by weiningtry7** [comment]
change kSecAttrAccessibleAlways to kSecAttrAccessibleAfterFirstUnlock, the (OSStatus) status = -25300 it cause that uninstall the app, thd uid is always changed，because keychain can not access.

**Comment by mikehardy** [comment]
@weiningtry7 do you have a PR you could propose? we merge PRs pretty well here when they're explained and the author tests them etc

**Pull request merged**
