### PR TITLE
feat(windows): implementation of EnergySaverStatusChanged to emitt event RNDeviceInfo_powerStateDidChange

### LINKED ISSUE #1518: Support for usePowerState or RNDeviceInfo_powerStateDidChange doesn't work in windows
## Summary
Support for Hook **usePowerState** or event **RNDeviceInfo_powerStateDidChange** is not available on windows platform

|             |     |
| ----------- | --- |
| Version     | 10.4.0 |
| Affected OS | Windows |
| OS Version  |11|

## Current behavior

Support for Hook **usePowerState** or event **RNDeviceInfo_powerStateDidChange** is not available on windows platform, Have checked the code and found that this event is not subscribed in windows

## Expected behavior

We should be get event RNDeviceInfo_powerStateDidChange on windows platform too

### PR DESCRIPTION
**Pull request by sohail-p**
feat(windows): implementation of EnergySaverStatusChanged to emitt event RNDeviceInfo_powerStateDidChange

add subscription to EnergySaverStatusChanged in Initialize and sent event RNDeviceInfo_powerStateDidChange with latest powerstate details

## Description

Fixes #1518 

## Compatibility

| OS      | Existing | Implemented |
| ------- | :---------: | :---------: |
| iOS     |    ✅     |    ❌     |
| Android |    ✅     |    ❌     |
| Windows |    ❌     |    ✅     |

## Checklist

* [x] I have tested this on a device/simulator for each compatible OS
* [ ] I added the documentation in `README.md`
* [ ] I updated the typings files (`privateTypes.ts`, `types.ts`)
* [ ] I added a sample use of the API (`example/App.js`)

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
Wow,, that's nice and tidy. Looks good to me - though I'll admit I know nothing of windows programming, this diff is tiny and I don't see anything obviously wrong with it. 🤞 😄

**Comment by sohail-p** [comment]
@mikehardy There seems to be some issue with Android Emulator, would you be able to check?

**Comment by sohail-p** [comment]
> > @mikehardy There seems to be some issue with Android Emulator, would you be able to check?
> 
> No, but I'm happy to merge PRs with a basis in evidence from any sort of investigation

@mikehardy From logs it shows that Emulator is outdated we need to manually update it
image
https://github.com/react-native-device-info/react-native-device-info/actions/runs/4533570279/jobs/7994704131?pr=1519#step:15:31

**Comment by mikehardy** [comment]
It's just flaky, sometimes github infra is so slow that it can't boot an emulator in time - you are correct in assuming that there's no way your change could affect it, but also after a few re-runs and a new day, it all went green anyway ;-)

**Pull request merged**
