### PR TITLE
Remove old install referrer api

### LINKED ISSUE #1146: Android Intent Redirection Vulnerability
## Summary

|             |     |
| ----------- | --- |
| Version     | 7.3.1   |
| Affected OS | android   |

## Current behavior
When we added `react-native-device-info` and used some functions like `getVersion()`, after releasing a version on google play, we received an email (from google play console) that says about **Intent Redirection Vulnerability** . You can find more info about the issue at this [link](https://support.google.com/faqs/answer/9267555?hl=en)

## Expected behavior

Clearing error and warning alert on google play console

## Suggestion resolve

According to the above Google Help link, ensuring that the extracted Intent is from a trustworthy source can resolve the problem. 
```
// check if the originating Activity is from trusted package
 if (getCallingActivity().getPackageName().equals(“known”)) {
   Intent intent = getIntent();
   // extract the nested Intent
   Intent forward = (Intent) intent.getParcelableExtra(“key”);
   // redirect the nested Intent
   startActivity(forward);
 }
```

### PR DESCRIPTION
**Pull request by nicoburns**
## Description

Fixes #1146

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    N/A    |
| Android |    ✅     |
| Windows |    N/A     |

## Checklist

* [ ] I have tested this on a device/simulator for each compatible OS
* [ ] I added the documentation in `README.md`
* [ ] I mentioned this change in `CHANGELOG.md`
* [X] I updated the typings files (`privateTypes.ts`, `types.ts`) (not necessary)
* [X] I added a sample use of the API (`example/App.js`) (not necessary)

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
This LGTM, thanks @nicoburns (and @Minishlink) !

**Comment by mikehardy** [comment]
Should release 7.4.0 soon (hopefully today?) as I have another change already queued up for it, sorry I don't just have semantic release bot installed to make it live immediately

Feel free to use patch-package of course, it's on main branch now so you know you'll converge and can easily evict the patch from your project next release

**Comment by nicoburns** [comment]
Thanks @mikehardy

FYI I tried removing the AndroidManifest.xml entirely. But it seems that that is required for android packages to be picked up by gradle at all.

**Comment by mikehardy** [comment]
Very interesting, not expected on the complete removal thing, I saw the attempt and revert and assumed it had a reason, good to know the reason, thanks for mentioning it

**Comment by mikehardy** [comment]
v7.4.0 is out just now with this, thanks!

**Pull request merged**
