### PR TITLE
feat(android): implemented getSupportedMediaTypeList method

### PR DESCRIPTION
**Pull request by Nikunj-bisht**
## Description

Added `getSupportedMediaTypeList()` that allows to find supported Codecs for device

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ❌     |
| Android |    ✅     |
| Windows |    ❌     |

## Checklist

* [X] I have tested this on a device/simulator for each compatible OS
* [X] I added the documentation in `README.md`
* [X] I updated the typings files (`privateTypes.ts`, `types.ts`)
* [X] I added a sample use of the API (`example/App.js`)

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
Now this PR is a thing of beauty!

**Review by schie — APPROVED** [review]
:shipit:

**Comment by Nikunj-bisht** [comment]
@mikehardy as all checks has passed can you please merge this pr

**Comment by mikehardy** [comment]
Sure, note that maintainers sleep and have patience please. I checked it alike 9pm my time and it's only 6am now. I have to get my kid to school. Should I drop what I'm doing it should you be okay with waiting a bit...

**Pull request merged**
