### PR TITLE
chore(example): fix appium deps for Windows tests

### PR DESCRIPTION
**Pull request by jaimecbernardo**
Fixes Windows actions fails by setting `appium`, `selenium-appium` and `selenium-webdriver` versions to the latest known compatible versions with `WinAppDriver`.
Updates `refresh-example.sh`.
This PR is meant to land on top of `example-cleanup` branch PR https://github.com/react-native-device-info/react-native-device-info/pull/1154.

### CODE REVIEW

**Comment by mikehardy** [comment]
This is fantastic, thank you very much for helping keep this running. I'm about to add the macosx port as well and I'm adding in CI for everything and trying to get it updated first so it has a solid base

**Comment by mikehardy** [comment]
Okay - I just checked this out and I incorporated it into my change - not sure how long it would have taken me to figure that out, thanks again

https://github.com/react-native-device-info/react-native-device-info/pull/1154/files#diff-33d7b5489cc37994ca552f5981ea921127fb767dbf7925cd40e953bc7f50d2f3R45-R49

**Comment by mikehardy** [comment]
@jaimecbernardo I have found the yarn installs brittle in CI (really, over enough time everything that depended on a remote network resource fetch has failed me at some point - yarn is just most frequent) but I've had great luck with a retry action, you might like this little bit of CI github action magic and perhaps it could help you in other projects:

https://github.com/react-native-device-info/react-native-device-info/pull/1154/files#diff-04640e218d8f0ac69a9deef45384bf1eea13ac5496f485c295bf43beed4bbc28

**Comment by jaimecbernardo** [comment]
Thank you!

**Pull request closed without merging**
