### PR TITLE
fix(iOS): syncUniqueId doesn't create a new random ID if there is no access to IDFV

### PR DESCRIPTION
**Pull request by InkOut**
## Description

Fixed syncUniqueId so that it doesn't create a new random ID if there is no access to IDFV

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |
| Windows |    ✅     |

## Checklist

* [+] I have tested this on a device/simulator for each compatible OS
* [+] I added the documentation in `README.md`
* [-] I mentioned this change in `CHANGELOG.md`
* [+] I updated the typings files (`privateTypes.ts`, `types.ts`)
* [+] I added a sample use of the API (`example/App.js`)

### CODE REVIEW

**Review by mikehardy — CHANGES_REQUESTED** [review]
I'm +1 on this change but the documentation in the comment above the method, and the method description in the readme are now incorrect, and that's just as important as the code change. Can you update those to indicate they now delegate to getUniqueId on iOS if IDFV is not available?

**Comment by InkOut** [comment]
@mikehardy thank you for your comment. I think I've fixed readme.

**Review by mikehardy — APPROVED** [review]
Ok - LGTM - thanks - Final question - this is just about how to release it - to me this is actually a point release - semantic-version patch. I don't believe this changes anything for installed users - is that correct? I am perfectly fine releasing a breaking change / semver major if this changes things for installed users but I can't see how it would.

What do you think?

**Comment by InkOut** [comment]
Yes, i'm +1 on semantic-version patch:
1. I would say that it's more a bug fix, not a breaking change. Sync should sync without others updates
2. I don't think there are more than 10 users using this function

**Comment by InkOut** [comment]
temporary closing

**Comment by mikehardy** [comment]
Even if 1 person is using semantic version says if it's breaking, it's breaking - which is fine! I'll just bump the right part of the version number
But is sounds like you agree that existing users will not be affected, which means patch release yes

**Comment by Bardiamist** [comment]
Hey, `syncUniqueId` was added for [another purpose](https://github.com/react-native-device-info/react-native-device-info/issues/922#issuecomment-585027771). After this PR logic be another and will not help after restore second device from iCloud backup if no access to IDFV. Not sure why you need this change but if you need it then consider to add new method instead change `syncUniqueId`.

**Pull request closed without merging**
