### PR TITLE
Example update WIP - needs windows testing, likely broken until fixed

### PR DESCRIPTION
**Pull request by mikehardy**
## Description

Fixes #<issue-number>

Added `yourNewMethodName()` that allows ...

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅❌     |
| Android |    ✅❌     |
| Windows |    ✅❌     |

## Checklist

* [ ] I have tested this on a device/simulator for each compatible OS
* [ ] I added the documentation in `README.md`
* [ ] I updated the typings files (`privateTypes.ts`, `types.ts`)
* [ ] I added a sample use of the API (`example/App.js`)

### CODE REVIEW

**Comment by tero-paananen** [comment]
I ran command `npx react-native run-windows --arch x64` in `react-native-device-info/example` folder and example started on my Windows 10.
device-info

**Comment by mikehardy** [comment]
Secret MacBookPro user or is something wrong :laughing: :thinking:  - thanks very much for checking

**Comment by mikehardy** [comment]
This one is actually close to working (or stated differently: I think it actually is working), I just haven't had time to run it through a last check on all platforms. Hopefully soon

**Comment by mikehardy** [comment]
Superceded by #1390 which does work! Just waiting on it to finish CI

**Pull request closed without merging**
