### PR TITLE
docs(README): update README for proguard rule

### LINKED ISSUE #1607: Android app crashing on start-up due to NullPointerException at com.android.installreferrer.api.onServiceConnected
## Summary

Experiencing app crashes only with APKs from downloaded and installed from Google Play Store on physical devices only.

Apologies in advance as this initial bug report is going to be a bit bare bones in the hopes of being pointed in the right direction to help provide what's needed to fix.

|             |     |
| ----------- | --- |
| Version     | ^10.12.0   |
| Affected OS | android   |
| OS Version  | 11   |

## Current behavior

On start-up of the app it crashes with the following error

```
java.lang.NullPointerException
	at com.android.installreferrer.api.b$b.onServiceConnected(SourceFile:24)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2207)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2240)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8248)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

## Expected behavior

Crash free

## Additional information

I've confirmed that removing this package from my application prevents the crash from happening.

I am also not attempting to use any install referrer utils here.

`react-native version 0.73.3`

### Pro-guard - not related

Pro-guard is enabled in my application however, disabling this does not fix the issue nor is it fixed by following the pro-guards steps within the README.

### Build Gradle/dependency

I've also explicitly attempted to explicitly include the dependency for `com.android.installreferrer:installreferrer` (versions ^1.1.1 and ^2.2) to no avail.

-----

Thanks in advance, I am going to continue trying to nail down the exact root cause but in the meantime appreciate any help.

### PR DESCRIPTION
**Pull request by jwhenshaw**
In order to avoid Null Pointer Exception

## Description
When using this package with ProGuard enabled, on start-up of the app it crashes with the following error
```
java.lang.NullPointerException
	at com.android.installreferrer.api.b$b.onServiceConnected(SourceFile:24)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2207)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2240)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8248)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

Fixes #1607

## Checklist

* [x] I have tested this on a device/simulator for each compatible OS
* [x] I added the documentation in `README.md`
* [ ] I updated the typings files (`privateTypes.ts`, `types.ts`)
* [ ] I added a sample use of the API (`example/App.js`)

### CODE REVIEW

**Comment by jwhenshaw** [comment]
> Is there any referencing pro-guard / android documentation regarding this change? 

Not that I can find I'm afraid.

**Comment by jwhenshaw** [comment]
An alternative cause that caused me to witness this recently was that I begin using OpenJDK17 over 11.

And with 17 there is a [note on behaviour changes](https://developer.android.com/about/versions/14/behavior-changes-14#core-libraries)
> ProGuard issues: In some cases, the addition of the [java.lang.ClassValue](https://developer.android.com/reference/java/lang/ClassValue) class causes an issue if you try to shrink, obfuscate, and optimize your app using ProGuard. The problem originates with a Kotlin library that changes runtime behaviour based on whether Class.forName("java.lang.ClassValue") returns a class or not. If your app was developed against an older version of the runtime without the java.lang.ClassValue class available, then these optimizations might remove the computeValue method from classes derived from java.lang.ClassValue

and given `Class.forName` is something we utilise where the issue was found points to a likely candidate.

Let me see if I can hop back to OpenJDK11 and reproduce the issue faced.

**Comment by jwhenshaw** [comment]
> Let me see if I can hop back to OpenJDK11 and reproduce the issue faced.

Went back to `react-native 0.72.10` and build with both Java 11 and 17 and faced no issues with the existing proguard rules.

**Review by mikehardy — APPROVED** [review]
I'm not going to deny someone's objective testing results (and your testing was pretty thorough on the linked issue comment!) - plus this is now a superset of the previous definition so it should meet the "do no harm" criteria with regard to correctness, while having a possible side effect of bloating a release APK just a touch.

Correctness >> slight APK size increase, so I'm +1 on this

@schie do you still have reservations or is this good to go for you?

**Review by schie — APPROVED** [review]
:shipit:

**Comment by meftunca** [comment]
The problem still persists. I updated proguard-rules but my problem is not solved.

**Comment by mikehardy** [comment]
Hi @meftunca ! Have you posted about this issue before? I don't see any comments from you on the related issue or the PR.

I may have missed it, but assuming you have not commented yet, no one can fix your problem without details on your problem. I'd suggest a new issue.

https://stackoverflow.com/help/how-to-ask
https://stackoverflow.com/help/minimal-reproducible-example

**Comment by meftunca** [comment]
@mikehardy I'm so sorry. Since my English is not good, I was trying to create and transfer it in a separate draft, but I wrote an incomplete comment. I was able to solve the problem and I apologize again for disturbing you. 

The problem was probably caused by forgetting to clear the cache and after clearing it worked as expected

**Pull request merged**
