### PR TITLE
[WIP] Added get screen dimensions

### PR DESCRIPTION
**Pull request by gh-clement-taboulot**
## Description

Added `getScreenDimensions()` that allows to get some screen specifications.

On iOS we can get screen dimensions in pt, px and mm.
On Android we can get screen dimensions in dp, px, mm. => **WIP**

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅    |
| Android |    ✅     |
| Windows |    ❌     |

## Checklist

* [x] I have tested this on a device/simulator for each compatible OS
* [ ] I added the documentation in `README.md`
* [ ] I mentioned this change in `CHANGELOG.md`
* [x] I updated the typings files (`privateTypes.ts`, `types.ts`)
* [x] I added a sample use of the API (`example/App.js`)

### CODE REVIEW

**Comment by mikehardy** [comment]
will close shortly in absence of feedback

**Comment by taboulot** [comment]
@mikehardy 

Sorry for the lateness of my response I was off.

I understand your hesitation. But as react-native-device-info user I really see it as the place where I can find informations relative to my device specifications: model, macadress, etc.. 🧐

And I see screen dimensions as a device specification.

I asked to developers around me and they had the same feeling 😄

**Comment by mikehardy** [comment]
I empathize with the point of view but the *safely useful* portion of the screen (which is the useful answer) is quite dynamic. It is not an intrinsic part of the device, it changes based on usage and current circumstance. I maintain react-native-safe-area-context is the correct home, and is actively developed. If they won't accept the functionality then we can see about it here - if that's the case in the end come back here and link the PR they rejected and we'll handle that as it may happen

**Comment by mrousavy** [comment]
It's also worth mentioning that the **Dimensions** API in react-native is completely broken since a really long time and facebook didn't really care about that. See: https://github.com/react-native-community/discussions-and-proposals/issues/291

**Pull request closed without merging**
