### PR TITLE
fix(windows): bump WindowsTargetPlatformMinVersion

### PR DESCRIPTION
**Pull request by TatianaKapos**
## Description

In RNW .72, we bump WinUI from 2.7 to 2.8 which targets a higher TargetPlatformMinVersion. This PR bumps the WindowsTargetPlatformMinVersion to the correct version for RNW .72

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    N/A     |
| Android |    N/A      |
| Windows |    ✅     |

## Checklist

* [X] I have tested this on a device/simulator for each compatible OS (tested on React Native Gallery)

### CODE REVIEW

**Comment by TatianaKapos** [comment]
@mikehardy would you mind looking at this PR when you have the chance? :) It blocks RNW apps from using .72

**Review by mikehardy — APPROVED** [review]
Passes local testing (of course it would, but it was good to see my local react-native-windows setup was working)
Queueing for merge + release while I work through updating the example and the CI test definitions versions

**Comment by mikehardy** [comment]
The e2e failures are unrelated to this PR, but this run proves PR builds with older Visual Studio (v16) which is a plus

Will merge this

I've proved locally and in CI that react-native-windows will *not* in fact build without this, as of 0.72, which is the whole point
I've proved locally (and will shortly in CI) that it builds on newer Visual Studio / react-native-windows 0.72 as well

Will then rebase my example refresh to 0.72 on top of this, that should go green and then we're all fresh and up to date. 

Cheers

**Comment by mikehardy** [comment]
Hey @TatianaKapos - would you know the best way to resolve a missing transitive dependency in CI here?

I'm seeing this after updating to react-native-windows 0.72 in CI, but it works for me locally just fine:

```
- Build failed with message D:\a\react-native-device-info\react-native-device-info\example\node_modules\react-native-device-info\windows\RNDeviceInfoCPP\RNDeviceInfoCPP.vcxproj(152,5): error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is D:\a\react-native-device-info\react-native-device-info\example\windows\\packages\Microsoft.Windows.CppWinRT.2.0.210312.4\build\native\Microsoft.Windows.CppWinRT.props.. Check your build configuration.
``

https://github.com/react-native-device-info/react-native-device-info/actions/runs/5416532711/jobs/9847408770#step:10:5768

I may be able to just stubbornly bull my way through it but if you or someone on your team knows already, I would really appreciate any help 🙏

**Comment by TatianaKapos** [comment]
Hi @mikehardy! Just saw this, thanks for getting to this so fast, I really appreciate it! :)

Our dev who does our CI for our own sample-apps is on vacation for the long weekend, but I'll tag him here for when he gets back! [jonthysell](https://github.com/jonthysell). This might not be the culprit, but RNW .72 needs to run on Visual Studio 2022. I know when I bumped our CI to .71 I had to change from windows-2019 to windows-2022? could be worth the try!

Also attaching our sample CI if you want to compare the two: https://github.com/microsoft/react-native-windows-samples/tree/main/.github/workflows

**Comment by mikehardy** [comment]
Yeah I thought the same but I moved to windows-latest runner and specified a [17.5,18) range for the setup-msbuild action

I thought I got ever right, I did try 😂

**Pull request merged**
