### PR TITLE
fix(iOS): Adds iPad Air 4th gen name description.

### PR DESCRIPTION
**Pull request by jcarioti**
## Description

Adds iPad Air 4th gen name description.

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ❌     |
| Windows |    ❌     |

## Checklist

* [ x] I have tested this on a device/simulator for each compatible OS
* [ n/a] I added the documentation in `README.md`
* [ n/a] I updated the typings files (`privateTypes.ts`, `types.ts`)
* [ n/a] I added a sample use of the API (`example/App.js`)

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
This looks good to me - and thank you for taking the time to help out! It's marked as draft, are you intending to add to it or change it, or would you like to merge + release it?

**Comment by mikehardy** [comment]
The conventional title check failure is okay - it's extra picky about single-commit PRs as a reminder that we need to squash-merge them to get the conventional commit title correct as github uses the commit title for single-commit PRs, not the PR title. It's not a problem

**Comment by jcarioti** [comment]
I didn't intend on making the PR a draft. It can be merged whenever is convenient.

**Comment by mikehardy** [comment]
Excellent - automated release with your change in 3....2.....1...

Thanks again!

**Pull request merged**
