### PR TITLE
feat: Added get device id for windows

### PR DESCRIPTION
**Pull request by JerryMacedoCastro**
Added `getDeviceId()` on windows that allows get device ID information

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |
| Windows |    ✅    |

## Checklist

* [x] I have tested this on a device/simulator for each compatible OS
* [x] I added the documentation in `README.md`
* [x] I updated the typings files (`privateTypes.ts`, `types.ts`)
* [x] I added a sample use of the API (`example/App.js`)

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
Nice! Seams reasonable - I'm inclined to merge if CI passes - have you personally run the example and seen this work? I don't have a windows testing rig so the burden of testing is much heavier on the proposer for windows PRs unfortunately

**Comment by JerryMacedoCastro** [comment]
> Nice! Seams reasonable - I'm inclined to merge if CI passes - have you personally run the example and seen this work? I don't have a windows testing rig so the burden of testing is much heavier on the proposer for windows PRs unfortunately

**Review by achipa — APPROVED** [review]

**Comment by mikehardy** [comment]
For some reason the windows CI failed on this one - I just re-ran it in case it was flaky, but if the error reports, it needs attending prior to merge

**Comment by JerryMacedoCastro** [comment]
@mikehardy I guess it's ok now

**Comment by mikehardy** [comment]
Very interesting - must have just been a flake, definitely happens when herding the cats in CI. Thanks for the reminder or I might not have swept through here again for a bit.

**Comment by mikehardy** [comment]
our auto-release bot will kick out a new release for this in minutes, thanks again for posting it! really appreciate any help keeping the windows side of thing useful + up to date

**Comment by datacana** [comment]
on Windows 11 and react-native-windows 66.5
getDeviceId() returns "NA"

**Comment by mikehardy** [comment]
@datacana did it used to work on windows 10? stated differently: have you personally ever seen this work and now it's not working? Or is this your first attempt, and with the example app on windows 11 it does not work?

**Comment by achipa** [comment]
It works for me on Win11, though I have not tried 66.x. Note that if there was a problem reading the id, you'd be getting `unknown` as the return string, not `NA`. If the device is not an OEM device (ie a custom windows desktop build), then there will be no ID for it (NA is a valid response in those cases). In practical terms, I believe this API is just a fancy (UWP friendly) wrapper for HKEY_LOCAL_MACHINE\HARDWARE\DESCRIPTION\System\BIOS\SystemSKU.

**Comment by mikehardy** [comment]
That smells like a docs PR to that API to forestall confusion :smile: :memo: 
good catch on NA vs unknown, I missed that clue

Here's the code line, FWIW,

https://github.com/react-native-device-info/react-native-device-info/blob/1a10a875c840bbe1ea0cb00fed592974d32d5f32/windows/code/RNDeviceInfoCPP.h#L637

**Pull request merged**
