### PR TITLE
testing memoized string getters and supported-platform-info

### PR DESCRIPTION
**Pull request by schie**
## Description

re #1108

- updates `getters` test file to be more scalable
- adds testing for memoized string getter functions
- fixes a mock used internally only (found by testing)
- adds testing for `supported-platform-info`

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |
| Windows |    ✅     |

## Checklist

* [X] I have tested this on a device/simulator for each compatible OS
* [ ] I added the documentation in `README.md`
* [ ] I mentioned this change in `CHANGELOG.md`
* [ ] I updated the typings files (`privateTypes.ts`, `types.ts`)
* [ ] I added a sample use of the API (`example/App.js`)

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
Nice, sorry for the delay 😅  but thanks for these!

**Comment by schie** [comment]
no worries.

I should have the vast majority of the remaining tests ready sometime this weekend.

**Comment by mikehardy** [comment]
the notification from your comment actually served as a reminder to tag that one :-)

**Comment by schie** [comment]
Cheers!

**Pull request merged**
