### PR TITLE
feat(windows): implement additional methods

### PR DESCRIPTION
**Pull request by jaimecbernardo**
## Description

Add Windows implementation for the following methods:
- `getBaseOs()`
- `getBuildId()`
- `getFontScale()`
- `getFreeDiskStorage()`
- `getInstallerPackageName()`
- `getInstallReferrer()`
- `getPowerState()`
- `getTotalDiskCapacity()`
- `getUsedMemory()`
- `isBatteryCharging()`

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| Windows |    ✅     |

## Checklist

* [x] I have tested this on a device for Windows
* [x] I added the documentation in `README.md`

### CODE REVIEW

**Comment by jaimecbernardo** [comment]
Hi @mikehardy ,
I've opened this PR to land after https://github.com/react-native-device-info/react-native-device-info/pull/1113 lands.
It's a draft for now, but I'll rebase it and mark it as a proper PR after https://github.com/react-native-device-info/react-native-device-info/pull/1113 is merged.

**Comment by mikehardy** [comment]
fantastic @jaimecbernardo I just returned yesterday and am slowly grinding through the backlog now, hoping to be caught up here by Monday or Tuesday

**Comment by jaimecbernardo** [comment]
Thank you for merging https://github.com/react-native-device-info/react-native-device-info/pull/1113 , which this PR depended on .
I've now rebased this PR on top of current master and properly opened it as a PR instead of a Draft.
It's now ready for review.

**Comment by jaimecbernardo** [comment]
Nevermind, it looks like the CI is failing when building.
I'll try to see if I can replicate this issue locally and update this PR.

**Comment by jaimecbernardo** [comment]
It looks like CI was failing because the environment was using a recent version of Visual Studio (>=16.8) that caused an error building react-native-windows:
https://github.com/microsoft/react-native-windows/issues/6495

Running `yarn upgrade react-native-windows` and committing the `yarn.lock` files allows the example to build with Visual Studio >= 16.8 and the tests are now passing.

**Review by mikehardy — APPROVED** [review]
Nice! LGTM - thanks @jaimecbernardo

**Comment by mikehardy** [comment]
It's all live now :rocket:  https://github.com/react-native-device-info/react-native-device-info/releases/tag/v7.2.0

**Comment by jaimecbernardo** [comment]
Thanks a lot for the quick turnaround @mikehardy 😃 
Great work!

**Pull request merged**
