### PR TITLE
feat: Add isWiredHeadphonesConnected and IsBluetoothHeadphonesConnected

### PR DESCRIPTION
**Pull request by hrastnik**
## Description

This PR adds two new methods `isWiredHeadphonesConnected` and `isBluetoothHeadphonesConnected` and their sync versions. I've come across the need to check if I have a BT headset connected, but since the existing `isHeadphonesConnected` method checks for either BT or wired headset I've decided to extract the specific methods.

## Compatibility

Same as `isHeadphonesConnected`  - supports Android, iOS and VisionOS.

## Checklist

* [X] I have tested this on a device/simulator for each compatible OS
* [X] I added the documentation in `README.md`
* [X] I updated the typings files (`privateTypes.ts`, `types.ts`)
* [X] I added a sample use of the API (`example/App.js`)

### CODE REVIEW

**Comment by hrastnik** [comment]
Any change you can approve this? 
@mikehardy @machour @GantMan @Johan-dutoit @schie

**Review by mikehardy — APPROVED** [review]
sorry - haven't been paying attention to notifications here but you got me with the direct ping ;-)
does look well done, there is an opportunity to eliminate some code duplication by having the general headphone check delegate to the two new specific headphones checks but I consider that an optimization,  I can merge this now
would be cool to have a follow-up that de-duplicated that code by doing the internal method delegation though...

thanks!

**Comment by mikehardy** [comment]
I am closing and reopening only because this typically kicks off a fresh attempt at CI

**Comment by mikehardy** [comment]
CI was a mess. Cleaned it up with #1638 then rebased this on top of the merged result of that one. CI should go green now, if it does I can merge...

**Pull request merged**
