### PR TITLE
Add isCatalyst

### LINKED ISSUE #1127: In Catalyst, app using getSystemName() reports as "iOS" on Big Sur
In Catalyst, app using getSystemName() reports as "iOS" on Big Sur. Probably be an easy fix though.

### PR DESCRIPTION
**Pull request by marcosrdz**
## Description

Fixes #1127

Added `isCatalyst()` that allows the developer to know whether the app is running on iOS or Mac Catalyst

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ❌     |
| Windows |    ❌     |

## Checklist

* [ ] I have tested this on a device/simulator for each compatible OS
* [x] I added the documentation in `README.md`
* [ ] I mentioned this change in `CHANGELOG.md`
* [x] I updated the typings files (`privateTypes.ts`, `types.ts`)
* [ ] I added a sample use of the API (`example/App.js`)

### CODE REVIEW

**Comment by mikehardy** [comment]
Hi there! I certainly like the idea of an API that signals we are working on catalyst, but I am not sure if this is the way.

Here is my doubt: should https://github.com/react-native-device-info/react-native-device-info#getsystemname actually be where this is done, and return macOS ? (and also perhaps tvOS, iPadOS, depending) ? I think that could work

In fact, checking the Flutter device_info code, we do the equivalent thing: 
- react-native: https://github.com/react-native-device-info/react-native-device-info/blob/55108da452fbe17231da968d2016011ad402d8ae/ios/RNDeviceInfo/RNDeviceInfo.m#L60
- flutter: https://github.com/flutter/plugins/blob/06530f9d3da4e80a818c3d3c0ec34fe2084b4abf/packages/device_info/device_info/ios/Classes/FLTDeviceInfoPlugin.m#L25

What I do not want to see is isCatalyst, isTvOS etc for all the fracturing Apple types, so even if getSystemName is not the place to do it exactly, I would want a single API like getSystemName


Perhaps their extra information chunk provides the information:
https://github.com/flutter/plugins/blob/06530f9d3da4e80a818c3d3c0ec34fe2084b4abf/packages/device_info/device_info/ios/Classes/FLTDeviceInfoPlugin.m#L31-L37

**Comment by marcosrdz** [comment]
> Hi there! I certainly like the idea of an API that signals we are working on catalyst, but I am not sure if this is the way.
> 
> 
> 
> Here is my doubt: should https://github.com/react-native-device-info/react-native-device-info#getsystemname actually be where this is done, and return macOS ? (and also perhaps tvOS, iPadOS, depending) ? I think that could work
> 
> 
> 
> In fact, checking the Flutter device_info code, we do the equivalent thing: 
> 
> - react-native: https://github.com/react-native-device-info/react-native-device-info/blob/55108da452fbe17231da968d2016011ad402d8ae/ios/RNDeviceInfo/RNDeviceInfo.m#L60
> 
> - flutter: https://github.com/flutter/plugins/blob/06530f9d3da4e80a818c3d3c0ec34fe2084b4abf/packages/device_info/device_info/ios/Classes/FLTDeviceInfoPlugin.m#L25
> 
> 
> 
> What I do not want to see is isCatalyst, isTvOS etc for all the fracturing Apple types, so even if getSystemName is not the place to do it exactly, I would want a single API like getSystemName
> 
> 
> 
> 
> 
> Perhaps their extra information chunk provides the information:
> 
> https://github.com/flutter/plugins/blob/06530f9d3da4e80a818c3d3c0ec34fe2084b4abf/packages/device_info/device_info/ios/Classes/FLTDeviceInfoPlugin.m#L31-L37

This was the way we could determine if the app was running on iOS or macOS. On Catalina, it returns "Mac OS X", but on Big Sur it returns "iOS". Which means we can't tell where the app is running if the app is on Big Sur.

**Comment by mikehardy** [comment]
Your direct experience is invaluable, thanks for providing the extra details.

I think the normal word for these sorts of things is "flavor"
perhaps a getSystemFlavor ? and it could start by just returning "Catalyst" for catalyst builds but could also hold the rest of the fragments (iPadOS, tvOS, watchOS, etc) if that became a thing?

I don't want to have a bunch of independent system flags though

So - a simple name change to that and I'd merge and release today? Would that work for you?

**Comment by marcosrdz** [comment]
My concern this mixing those up is future-proof-ability. What if Catalyst extends to other Apple platforms? refactoring to separate tvOS from getSystemFlavor would be required and so on.

**Comment by mikehardy** [comment]
This is sort of a general cross platform problem. It's hard to guess the future but it's possible with a general interface to be more precise in what "flavor" returns. Perhaps it could be "Catalyst-implantOS" or "Catalyst-vrOS" or whatever if that happens?

**Comment by exotexot** [comment]
> What I do not want to see is isCatalyst, isTvOS etc for all the fracturing Apple types, so even if getSystemName is not the place to do it exactly, I would want a single API like getSystemName

I think a isCatalyst flag could be useful as it is more of a special edge case in apples ecosystem, but than again a popular one in the pre Apple Silicon era.

> This was the way we could determine if the app was running on iOS or macOS. On Catalina, it returns "Mac OS X", but on Big Sur it returns "iOS". Which means we can't tell where the app is running if the app is on Big Sur.

I also want to mention that getSystemVersion reports 14.2 (iOS) instead of (11.0) on BigSur. To detect BigSur than could be achieved via isCatalyst && getSystemVersion() > 11.

**Comment by mikehardy** [comment]
It seems there are a bunch of special edge cases for the Apple ecosystem though, and as mentioned I do not want a bunch of flags for them. Your detection hypothesis for detecting BigSur is useful but would be even better if the module actually did it instead of everyone having to implement it, and it could be behind a specific flavor response as well

I really do not want a bunch of flags, is there a way to make this work with a more general purpose getSystemFlavor type API?

**Comment by marcosrdz** [comment]
> > What I do not want to see is isCatalyst, isTvOS etc for all the fracturing Apple types, so even if getSystemName is not the place to do it exactly, I would want a single API like getSystemName
> 
> 
> 
> I think a isCatalyst flag could be useful as it is more of a special edge case in apples ecosystem, but than again a popular one in the pre Apple Silicon era.
> 
> 
> 
> > This was the way we could determine if the app was running on iOS or macOS. On Catalina, it returns "Mac OS X", but on Big Sur it returns "iOS". Which means we can't tell where the app is running if the app is on Big Sur.
> 
> 
> 
> I also want to mention that getSystemVersion reports 14.2 (iOS) instead of (11.0) on BigSur. To detect BigSur than could be achieved via isCatalyst && getSystemVersion() > 11.

I find isCatalyst a good approach given that its a special case that will definitely grow in the platform. Having "BigSur" if isCatalyst and > 11 will lead to the need to refactoring (especially after every release...also what about 11.1? Will it also say BigSur instead of whatever name they give it?). This approach wont work if the app isnt running with catalyst (rn macos for example).

**Review by mikehardy — CHANGES_REQUESTED** [review]
Okay, but please add it to the mocks, to the example app, I think one of the internal/PrivateTypes needs to be isCatalystSync ? (even though it's the same, yes), and ideally the changelog, then we can merge this and release

**Comment by marcosrdz** [comment]
> Okay, but please add it to the mocks, to the example app, I think one of the internal/PrivateTypes needs to be isCatalystSync ? (even though it's the same, yes), and ideally the changelog, then we can merge this and release

Will do. I'll aim to get that ready tonight.

**Comment by exotexot** [comment]
Alternatively, one could extended https://github.com/react-native-device-info/react-native-device-info#getDeviceType

Maybe it could also return "desktop" on windows and catalyst

**Comment by mikehardy** [comment]
I would be a lot happier with that - interesting thought @exotexot - and I think it conveys the information we need

**Comment by mikehardy** [comment]
I appreciate the work here and the collaboration - I went with a merge on adding "desktop" to getDeviceType as a preference to adding this specific flavor. I *believe* that will still allow the precision people want (ios + desktop? that's catalyst) and I *hope* it is more flexible then just a catalyst specific flag, but the discussion here was where we figured that out and that was valuable. We can revisit later if this decision turns out to be in error, as mentioned I hope "desktop" as a device type is flexible while still being specific enough but in a year+ we might decide it was bad choice.

it'll be in the next release shortly

Thanks!

**Pull request closed without merging**
